# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F8QRVDQTd4GUUL-05dogq9TnZRTVzV7C
"""

!pip install fastapi uvicorn pyngrok

from fastapi import FastAPI, HTTPException

app = FastAPI()


users = []
records = []


def find_user(user_id):
    for user in users:
        if user["id"] == user_id:
            return user
    return None

def check_role(user_id, allowed_roles):
    user = find_user(user_id)
    if not user or user["role"] not in allowed_roles:
        raise HTTPException(status_code=403, detail="Access Denied")

@app.post("/create_user")
def create_user(user_id: int, name: str, role: str):
    users.append({"id": user_id, "name": name, "role": role})
    return {"message": "User created"}


@app.post("/add_record")
def add_record(user_id: int, amount: float, type: str, category: str):
    check_role(user_id, ["admin"])

    record = {
        "id": len(records)+1,
        "amount": amount,
        "type": type,
        "category": category
    }
    records.append(record)
    return {"message": "Record added", "record": record}

@app.get("/records")
def get_records(user_id: int):
    check_role(user_id, ["admin", "analyst", "viewer"])
    return records

@app.get("/summary")
def get_summary(user_id: int):
    check_role(user_id, ["admin", "analyst"])

    income = sum(r["amount"] for r in records if r["type"] == "income")
    expense = sum(r["amount"] for r in records if r["type"] == "expense")

    return {
        "total_income": income,
        "total_expense": expense,
        "balance": income - expense
    }

from pyngrok import ngrok

ngrok.set_auth_token("ngrok config add-authtoken 35hsPzMi5AiUsM7oBYpG4gLg1US_5DyVVzKqEFisqcm47Yd53")

!pip install pyngrok

from pyngrok import ngrok
import uvicorn
import threading


!pkill ngrok


ngrok.set_auth_token("35hsPzMi5AiUsM7oBYpG4gLg1US_5DyVVzKqEFisqcm47Yd53")

public_url = ngrok.connect(8000)
print("Public URL:", public_url)


def run():
    uvicorn.run(app, host="0.0.0.0", port=8000)

threading.Thread(target=run).start()

@app.get("/users")
def get_users():
    return users
